language: php

preset: symfony

enabled:
    - short_array_syntax
    - concat_with_spaces
    - not_operator_with_successor_space

env:
  global:
    - MIN_PHP=7.1.3
    - setup=stable

matrix:
    include:
        - php: 7.1.3
        - php: 7.1
          env: deps=high
        - php: 7.2
          env: deps=low

    fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit
